variables:
  GIT_STRATEGY: "pull"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_CHECKOUT: "true"
# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: rust:latest

# Defines stages which are to be executed
stages:
  - build
  - test

# Run `cargo build` for the project with stable Rust
run-build:
  stage: build
  image: rust:latest
  script:
  - rustc --version && cargo --version
  - cargo build --release --jobs 1

run-test:
  stage: test
  image: rust:latest
  script:
  - cargo test
